import type { Locale } from "@/i18n";

const ar = {
  book: "احجز موعدك",
  whatsapp: "تواصل واتساب",
  call: "اتصل بنا",
  nav: { services: "الخدمات", doctors: "الأطباء", branches: "الفروع", contact: "تواصل" },
  services: { title: "خدماتنا", subtitle: "رعاية متكاملة لصحة وجمال ابتسامتك.", minutes: "دقيقة", from: "يبدأ من", bookThis: "احجز هذه الخدمة" },
  doctors: { title: "فريقنا الطبي", subtitle: "أطباء متخصصون يستمعون لك قبل أن يعالجوك." },
  branches: { title: "فروعنا", subtitle: "اختر الفرع الأقرب لك.", map: "الاتجاهات على الخريطة" },
  facts: { doctors: "أطباء متخصصون", services: "خدمة علاجية وتجميلية", branches: "فروع" },
  cta: { title: "جاهز لزيارتنا؟", subtitle: "اختر الخدمة والطبيب والوقت المناسب لك، واحجز في أقل من دقيقة." },
  footer: { poweredBy: "بإدارة", rights: "جميع الحقوق محفوظة." },
  heroCard: "من خدماتنا",
  booking: {
    title: "احجز موعدك",
    back: "العودة للموقع",
    steps: ["الخدمة", "الطبيب", "الموعد", "بياناتك"],
    chooseService: "ما الخدمة التي تحتاجها؟",
    chooseDoctor: "اختر الطبيب",
    anyDoctor: "أي طبيب متاح",
    anyDoctorHint: "نختار لك أقرب موعد متاح",
    chooseTime: "اختر اليوم والوقت",
    noTimes: "لا توجد مواعيد متاحة في هذا اليوم.",
    noDays: "لا توجد مواعيد متاحة خلال الأيام القادمة. تواصل معنا على واتساب.",
    loading: "نبحث عن المواعيد المتاحة…",
    yourDetails: "بياناتك",
    name: "الاسم الكامل",
    phone: "رقم الجوال",
    notes: "ملاحظات (اختياري)",
    consent: "أوافق على استخدام بياناتي لتأكيد الموعد والتذكير به.",
    summary: "ملخص الحجز",
    confirm: "تأكيد الحجز",
    sending: "جارٍ الحجز…",
    next: "التالي",
    prev: "السابق",
    change: "تغيير",
    at: "في",
    with: "مع",
    branch: "الفرع",
    done: "تم حجز موعدك",
    doneHint: "وصل طلبك للعيادة، وسيتواصل معك الفريق لتأكيد الموعد.",
    addToCalendar: "أضف إلى التقويم",
    another: "حجز موعد آخر",
    errors: {
      slot_unavailable: "هذا الوقت حُجز للتو. اختر وقتاً آخر.",
      too_many_bookings: "لديك عدة مواعيد قادمة بهذا الرقم. تواصل معنا لتعديلها.",
      invalid_phone: "رقم الجوال غير صحيح. مثال: 05XXXXXXXX",
      invalid_name: "اكتب اسمك الكامل.",
      clinic_not_found: "الحجز غير متاح حالياً.",
      error: "حدث خطأ. حاول مرة ثانية أو تواصل معنا على واتساب.",
    },
  },
  occasion: {
    founding_day: "يوم التأسيس ١٧٢٧م — يوم بدينا",
    national_day: "كل عام والوطن بخير — اليوم الوطني السعودي",
  },
};

export type SiteStrings = typeof ar;

const en: SiteStrings = {
  book: "Book an appointment",
  whatsapp: "WhatsApp us",
  call: "Call us",
  nav: { services: "Services", doctors: "Doctors", branches: "Branches", contact: "Contact" },
  services: { title: "Our services", subtitle: "Complete care for a healthy, confident smile.", minutes: "min", from: "From", bookThis: "Book this service" },
  doctors: { title: "Our doctors", subtitle: "Specialists who listen before they treat." },
  branches: { title: "Our branches", subtitle: "Choose the branch closest to you.", map: "Get directions" },
  facts: { doctors: "Specialist doctors", services: "Treatments", branches: "Branches" },
  cta: { title: "Ready to visit?", subtitle: "Pick the service, doctor and time that suit you — it takes under a minute." },
  footer: { poweredBy: "Powered by", rights: "All rights reserved." },
  heroCard: "Popular treatments",
  booking: {
    title: "Book an appointment",
    back: "Back to website",
    steps: ["Service", "Doctor", "Time", "Details"],
    chooseService: "What do you need?",
    chooseDoctor: "Choose a doctor",
    anyDoctor: "Any available doctor",
    anyDoctorHint: "We'll find the earliest time for you",
    chooseTime: "Pick a day and time",
    noTimes: "No times left on this day.",
    noDays: "No open times in the coming days. Please message us on WhatsApp.",
    loading: "Finding available times…",
    yourDetails: "Your details",
    name: "Full name",
    phone: "Mobile number",
    notes: "Notes (optional)",
    consent: "I agree to my details being used to confirm and remind me of this appointment.",
    summary: "Summary",
    confirm: "Confirm booking",
    sending: "Booking…",
    next: "Next",
    prev: "Back",
    change: "Change",
    at: "at",
    with: "with",
    branch: "Branch",
    done: "You're booked",
    doneHint: "The clinic has your request and will contact you to confirm it.",
    addToCalendar: "Add to calendar",
    another: "Book another",
    errors: {
      slot_unavailable: "That time was just taken. Please pick another.",
      too_many_bookings: "You already have several upcoming bookings with this number. Please contact us.",
      invalid_phone: "Invalid mobile number. Example: 05XXXXXXXX",
      invalid_name: "Please enter your full name.",
      clinic_not_found: "Online booking is unavailable right now.",
      error: "Something went wrong. Try again or message us on WhatsApp.",
    },
  },
  occasion: {
    founding_day: "Saudi Founding Day — since 1727",
    national_day: "Happy Saudi National Day",
  },
};

export const getSiteStrings = (lang: Locale) => (lang === "en" ? en : ar);
