import type { Locale } from "@/i18n";

const ar = {
  book: "احجز موعدك",
  whatsapp: "تواصل واتساب",
  call: "اتصل بنا",
  nav: { services: "الخدمات", doctors: "الأطباء", results: "النتائج", branches: "الفروع", contact: "تواصل" },
  services: { title: "خدماتنا", subtitle: "رعاية متكاملة لصحة وجمال ابتسامتك.", minutes: "دقيقة", from: "يبدأ من", bookThis: "احجز هذه الخدمة" },
  doctors: { title: "فريقنا الطبي", subtitle: "أطباء متخصصون يستمعون لك قبل أن يعالجوك.", bookWith: "احجز مع الطبيب" },
  branches: { title: "فروعنا", subtitle: "اختر الفرع الأقرب لك.", map: "الاتجاهات على الخريطة" },
  facts: { doctors: "أطباء متخصصون", services: "خدمة علاجية وتجميلية", branches: "فروع" },
  cta: { title: "جاهز لزيارتنا؟", subtitle: "اختر الخدمة والطبيب والوقت المناسب لك، واحجز في أقل من دقيقة." },
  footer: { poweredBy: "بإدارة", rights: "جميع الحقوق محفوظة." },
  heroCard: "من خدماتنا",
  hero: {
    chips: [["حجز فوري", "من جوالك في أقل من دقيقة"], ["مواعيد دقيقة", "بدون انتظار طويل"]],
    online: "حجز إلكتروني",
  },
  why: {
    eyebrow: "لماذا تختارنا؟",
    title: "راحتك ودقة العلاج، بلا تنازل.",
    items: [
      ["حجز فوري على مدار الساعة", "اختر الخدمة والطبيب والوقت من جوالك، ويصل طلبك للعيادة مباشرة."],
      ["مواعيد دقيقة بلا انتظار", "جدول منظم لكل طبيب يقلل وقت الانتظار ويحترم وقتك."],
      ["تذكير قبل الموعد", "تصلك رسالة تذكير على واتساب فيها رابط للتأكيد أو تغيير الموعد."],
      ["خطة علاج واضحة", "نشرح لك الخيارات والمدة والتكلفة قبل البدء، بدون مفاجآت."],
    ],
    noReminders: ["تواصل سهل", "فريق الاستقبال يتابع طلبك ويؤكد موعدك بسرعة."],
  },
  how: {
    eyebrow: "الحجز الذكي",
    title: "موعدك يُسجَّل في اللحظة نفسها.",
    text: "اختر الخدمة والطبيب والوقت المناسب. يظهر طلبك فوراً لفريق العيادة، ويصلك التأكيد والتذكير تلقائياً.",
    steps: [["اختر الموعد", "حدد الخدمة واليوم والوقت المتاح."], ["تأكيد فوري", "يصل طلبك للعيادة في نفس اللحظة."], ["تذكير تلقائي", "رسالة قبل الموعد مع رابط للتعديل."]],
  },
  cases: {
    eyebrow: "نتائج موثّقة بصرياً",
    title: "شاهد التحوّل بتفاصيله، لا بالوعود.",
    subtitle: "اسحب المؤشر في كل حالة لمقارنة البداية بالنتيجة.",
    before: "قبل",
    after: "بعد",
    slider: "مقارنة قبل وبعد",
    note: "تختلف مدة ونتائج العلاج من شخص لآخر حسب الفحص والحالة الصحية.",
  },
  faq: {
    eyebrow: "أسئلة شائعة",
    title: "أسئلة تمنحك وضوحاً أكبر.",
    items: [
      ["كيف أحجز موعد؟", "اضغط «احجز موعدك»، اختر الخدمة والطبيب والوقت، واكتب اسمك ورقم جوالك. يصل الحجز للعيادة فوراً."],
      ["هل أقدر أغيّر موعدي أو ألغيه؟", "نعم. يصلك رابط خاص بموعدك تقدر منه تأكيد الحضور أو تغيير الوقت أو الإلغاء، أو تواصل معنا على واتساب."],
      ["متى أحتاج أزور طبيب الأسنان؟", "ننصح بفحص دوري كل ستة أشهر، وبزيارة عاجلة عند ألم مستمر أو تورّم أو نزيف في اللثة."],
      ["وش أحضر معي في الزيارة الأولى؟", "بطاقة الهوية، وبطاقة التأمين إن وجدت، وأي أشعة أو تقارير سابقة إن كانت عندك."],
    ],
  },
  booking: {
    title: "احجز موعدك",
    back: "العودة للموقع",
    steps: ["الخدمة", "الطبيب", "الموعد", "بياناتك"],
    chooseService: "ما الخدمة التي تحتاجها؟",
    chooseDoctor: "اختر الطبيب",
    anyDoctor: "أي طبيب متاح",
    anyDoctorHint: "نختار لك أقرب موعد متاح",
    chooseTime: "اختر اليوم والوقت",
    noTimes: "لا توجد مواعيد متاحة في هذا اليوم.",
    noDays: "لا توجد مواعيد متاحة خلال الأيام القادمة. تواصل معنا على واتساب.",
    loading: "نبحث عن المواعيد المتاحة…",
    yourDetails: "بياناتك",
    name: "الاسم الكامل",
    phone: "رقم الجوال",
    phoneHint: "يصلك تأكيد الموعد على هذا الرقم.",
    morning: "الفترة الصباحية",
    evening: "الفترة المسائية",
    notes: "ملاحظات (اختياري)",
    consent: "أوافق على استخدام بياناتي لتأكيد الموعد والتذكير به.",
    privacy: "سياسة الخصوصية",
    summary: "ملخص الحجز",
    confirm: "تأكيد الحجز",
    sending: "جارٍ الحجز…",
    next: "التالي",
    prev: "السابق",
    change: "تغيير",
    at: "في",
    with: "مع",
    branch: "الفرع",
    done: "تم حجز موعدك",
    doneHint: "وصل طلبك للعيادة، وسيتواصل معك الفريق لتأكيد الموعد.",
    doneHintReminders: "وصل طلبك للعيادة، وستصلك رسالة تذكير على واتساب قبل الموعد فيها رابط للتأكيد أو التغيير.",
    manage: "إدارة الموعد",
    addToCalendar: "أضف إلى التقويم",
    another: "حجز موعد آخر",
    errors: {
      slot_unavailable: "هذا الوقت حُجز للتو. اختر وقتاً آخر.",
      too_many_bookings: "لديك عدة مواعيد قادمة بهذا الرقم. تواصل معنا لتعديلها.",
      invalid_phone: "رقم الجوال غير صحيح. مثال: 05XXXXXXXX",
      invalid_name: "اكتب اسمك الكامل.",
      clinic_not_found: "الحجز غير متاح حالياً.",
      error: "حدث خطأ. حاول مرة ثانية أو تواصل معنا على واتساب.",
    },
  },
  manageAppt: {
    title: "موعدك",
    status: { pending: "بانتظار التأكيد", confirmed: "مؤكد", completed: "تم", cancelled: "ملغي", no_show: "لم يحضر" },
    confirm: "تأكيد الحضور",
    confirmed: "شكراً، تم تأكيد حضورك.",
    reschedule: "تغيير الموعد",
    cancel: "إلغاء الموعد",
    cancelAsk: "هل تريد إلغاء الموعد فعلاً؟",
    cancelYes: "نعم، ألغِ الموعد",
    cancelled: "تم إلغاء الموعد.",
    rescheduled: "تم تغيير موعدك.",
    tooLate: "لا يمكن تغيير الموعد إلكترونياً قبل موعده بأقل من {hours} ساعة. تواصل مع العيادة.",
    pickTime: "اختر وقتاً جديداً",
    noTimes: "لا توجد أوقات متاحة في هذا اليوم.",
    back: "رجوع",
    contact: "تواصل مع العيادة",
    directions: "الاتجاهات",
    invalid: "هذا الرابط غير صالح أو انتهت صلاحيته.",
    error: "تعذّر تنفيذ الطلب. حاول مرة ثانية.",
    slotTaken: "هذا الوقت لم يعد متاحاً. اختر وقتاً آخر.",
  },
  occasion: {
    founding_day: "يوم التأسيس · يوم بدينا ١٧٢٧م",
    national_day: "اليوم الوطني السعودي ٩٦ · كل عام والوطن بخير",
  },
};

export type SiteStrings = typeof ar;

const en: SiteStrings = {
  book: "Book an appointment",
  whatsapp: "WhatsApp us",
  call: "Call us",
  nav: { services: "Services", doctors: "Doctors", results: "Results", branches: "Branches", contact: "Contact" },
  services: { title: "Our services", subtitle: "Complete care for a healthy, confident smile.", minutes: "min", from: "From", bookThis: "Book this service" },
  doctors: { title: "Our doctors", subtitle: "Specialists who listen before they treat.", bookWith: "Book with this doctor" },
  branches: { title: "Our branches", subtitle: "Choose the branch closest to you.", map: "Get directions" },
  facts: { doctors: "Specialist doctors", services: "Treatments", branches: "Branches" },
  cta: { title: "Ready to visit?", subtitle: "Pick the service, doctor and time that suit you — it takes under a minute." },
  footer: { poweredBy: "Powered by", rights: "All rights reserved." },
  heroCard: "Popular treatments",
  hero: {
    chips: [["Instant booking", "From your phone in under a minute"], ["On-time visits", "No long waits"]],
    online: "Online booking",
  },
  why: {
    eyebrow: "Why choose us",
    title: "Your comfort and precise care — no compromises.",
    items: [
      ["Book any time", "Pick the service, doctor and time from your phone; it reaches the clinic instantly."],
      ["On-time appointments", "An organised schedule for every doctor keeps waiting to a minimum."],
      ["Reminders before your visit", "A WhatsApp reminder with a link to confirm or reschedule."],
      ["A clear treatment plan", "We explain the options, time and cost before we start — no surprises."],
    ],
    noReminders: ["Easy to reach", "Our front desk follows up and confirms your visit quickly."],
  },
  how: {
    eyebrow: "Smart booking",
    title: "Your appointment is recorded instantly.",
    text: "Choose the service, doctor and time. The clinic sees your request right away, and confirmations and reminders arrive automatically.",
    steps: [["Pick a time", "Choose the service, day and an open slot."], ["Instant confirmation", "The clinic receives it the same moment."], ["Automatic reminder", "A message before your visit with a link to change it."]],
  },
  cases: {
    eyebrow: "Real results",
    title: "See the transformation, not just promises.",
    subtitle: "Drag the handle in each case to compare before and after.",
    before: "Before",
    after: "After",
    slider: "Before and after comparison",
    note: "Treatment time and results vary from person to person.",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions, answered.",
    items: [
      ["How do I book?", "Tap “Book an appointment”, pick the service, doctor and time, then enter your name and mobile. The clinic receives it instantly."],
      ["Can I change or cancel?", "Yes. You get a personal link to confirm, reschedule or cancel — or message us on WhatsApp."],
      ["How often should I see a dentist?", "A check-up every six months, and sooner for persistent pain, swelling or bleeding gums."],
      ["What should I bring?", "Your ID, insurance card if you have one, and any previous X-rays or reports."],
    ],
  },
  booking: {
    title: "Book an appointment",
    back: "Back to website",
    steps: ["Service", "Doctor", "Time", "Details"],
    chooseService: "What do you need?",
    chooseDoctor: "Choose a doctor",
    anyDoctor: "Any available doctor",
    anyDoctorHint: "We'll find the earliest time for you",
    chooseTime: "Pick a day and time",
    noTimes: "No times left on this day.",
    noDays: "No open times in the coming days. Please message us on WhatsApp.",
    loading: "Finding available times…",
    yourDetails: "Your details",
    name: "Full name",
    phone: "Mobile number",
    phoneHint: "Your confirmation is sent to this number.",
    morning: "Morning",
    evening: "Afternoon & evening",
    notes: "Notes (optional)",
    consent: "I agree to my details being used to confirm and remind me of this appointment.",
    privacy: "Privacy policy",
    summary: "Summary",
    confirm: "Confirm booking",
    sending: "Booking…",
    next: "Next",
    prev: "Back",
    change: "Change",
    at: "at",
    with: "with",
    branch: "Branch",
    done: "You're booked",
    doneHint: "The clinic has your request and will contact you to confirm it.",
    doneHintReminders: "The clinic has your request. You'll get a WhatsApp reminder before your visit with a link to confirm or change it.",
    manage: "Manage appointment",
    addToCalendar: "Add to calendar",
    another: "Book another",
    errors: {
      slot_unavailable: "That time was just taken. Please pick another.",
      too_many_bookings: "You already have several upcoming bookings with this number. Please contact us.",
      invalid_phone: "Invalid mobile number. Example: 05XXXXXXXX",
      invalid_name: "Please enter your full name.",
      clinic_not_found: "Online booking is unavailable right now.",
      error: "Something went wrong. Try again or message us on WhatsApp.",
    },
  },
  manageAppt: {
    title: "Your appointment",
    status: { pending: "Pending", confirmed: "Confirmed", completed: "Completed", cancelled: "Cancelled", no_show: "No-show" },
    confirm: "Confirm attendance",
    confirmed: "Thanks — your attendance is confirmed.",
    reschedule: "Change time",
    cancel: "Cancel appointment",
    cancelAsk: "Do you really want to cancel?",
    cancelYes: "Yes, cancel it",
    cancelled: "Your appointment was cancelled.",
    rescheduled: "Your appointment was moved.",
    tooLate: "Online changes close {hours} hours before the visit. Please contact the clinic.",
    pickTime: "Pick a new time",
    noTimes: "No times left on this day.",
    back: "Back",
    contact: "Contact the clinic",
    directions: "Directions",
    invalid: "This link is invalid or has expired.",
    error: "Something went wrong. Please try again.",
    slotTaken: "That time is no longer available. Please pick another.",
  },
  occasion: {
    founding_day: "Saudi Founding Day · since 1727",
    national_day: "Saudi National Day 96 · Happy National Day",
  },
};

export const getSiteStrings = (lang: Locale) => (lang === "en" ? en : ar);
